# Generated by Django 3.1.7 on 2021-03-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyTopicForeign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.TextField(db_column='stock_name')),
                ('stock_date', models.TextField(db_column='stock_date')),
                ('foreign_trading_volume', models.TextField(db_column='foreign_trading_volume')),
                ('foreign_rate', models.TextField(db_column='foreign_rate')),
                ('create_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'my_topic_foreign_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MyTopicInstitut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.TextField(db_column='stock_name')),
                ('stock_date', models.TextField(db_column='stock_date')),
                ('institut_trading_volume', models.TextField(db_column='institut_trading_volume')),
                ('create_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'my_topic_institut_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MyTopicNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.TextField(db_column='stock_code')),
                ('article_title', models.TextField(db_column='article_title')),
                ('article_url', models.TextField(db_column='article_url')),
                ('article_author', models.TextField(db_column='article_author')),
                ('article_date', models.TextField(db_column='article_date')),
                ('create_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'my_topic_news_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MyTopicPriceBuy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.TextField(db_column='stock_name')),
                ('stock_code', models.TextField(db_column='stock_code')),
                ('buying_price', models.TextField(db_column='buying_price')),
                ('buying_volume', models.TextField(db_column='buying_volume')),
                ('create_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'my_topic_price_buy_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MyTopicPriceSell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.TextField(db_column='stock_name')),
                ('stock_code', models.TextField(db_column='stock_code')),
                ('selling_price', models.TextField(db_column='selling_price')),
                ('selling_volume', models.TextField(db_column='selling_volume')),
                ('create_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'my_topic_price_sell_table',
                'managed': False,
            },
        ),
    ]
